// The manifest is generated by `npm run portfolio` from the camera originals.
// It carries each painting's true pixel dimensions, which is what lets the
// gallery lay itself out at the correct widths before any image downloads.

import { getAssetUrl } from '../utils/paths.js';

let cached = null;

export async function loadManifest() {
    if (cached) return cached;
    try {
        const res = await fetch(getAssetUrl('portfolio/manifest.json'), { cache: 'no-cache' });
        if (!res.ok) throw new Error(`manifest.json ${res.status}`);
        const data = await res.json();

        // Drop anything without usable dimensions rather than laying out a
        // zero-width frame.
        const paintings = (data.paintings || []).filter(p => p.aspect > 0 && p.file);
        cached = { ...data, paintings };
        return cached;
    } catch (e) {
        console.error('Could not load portfolio manifest — run `npm run portfolio`.', e);
        return { paintings: [] };
    }
}
